-- Add Personal Driver category to vehicle_category table
-- This category will appear in the ride categories

INSERT INTO vehicle_category VALUES(
"355",
"Personal Driver","私人司机","Osobní řidič","Personal Driver","Personlig chauffør","Chauffeur personnel","נהג אישי","निजी ड्राइवर","Osobisty kierowca","Личный водитель","Kişisel Şoför","개인 운전사","Personal na Driver","Pemandu Peribadi","Șofer personal","Motorista Pessoal","Προσωπικός οδηγός","Persoonlijke chauffeur","سائق شخصي","Autista personale","Personlig förare","Conductor personal","Personlig sjåfør","Persönlicher Fahrer","คนขับส่วนตัว",
"","","","","","","","","","","","","","","","","","","","","","","","","",
"","","","","","","","","","","","","","","","","","","","","","","","","",
"0",
"ic_personal_driver_EN.png","ic_personal_driver_EN.png","",
"image_personal_driver.svg",
"Service",
"","",
"2",
"Active",
"Icon",
"No",
"personal_driver_banner.jpg",
"Ride",
"",
"RideCategory",
"",
"0",
"{\"tBannerButtonText_EN\":\"Book Now\",\"tBannerButtonText_HI\":\"अभी बुक करें\",\"tBannerButtonText_AR\":\"احجز الآن\",\"tBannerButtonText_FR\":\"Réserver maintenant\",\"tBannerButtonText_ES\":\"Reservar ahora\",\"tBannerButtonText_DE\":\"Jetzt buchen\",\"tBannerButtonText_IT\":\"Prenota ora\",\"tBannerButtonText_PT\":\"Reserve agora\",\"tBannerButtonText_RU\":\"Забронировать\",\"tBannerButtonText_ZHCN\":\"立即预订\"}",
"",
"0.00",
"0.00",
"0",
"0.00",
"0",
"0",
"2",
"{\"lCatDescHomepage_EN\":\"\",\"lCatDescHomepage_HI\":\"\",\"lCatDescHomepage_AR\":\"\"}",
"{\"vCatDescbtnHomepage_EN\":\"\",\"vCatDescbtnHomepage_HI\":\"\",\"vCatDescbtnHomepage_AR\":\"\"}",
"{\"vCatNameHomepage_EN\":\"\",\"vCatNameHomepage_HI\":\"\",\"vCatNameHomepage_AR\":\"\"}",
"{\"vCatSloganHomepage_EN\":\"\",\"vCatSloganHomepage_HI\":\"\",\"vCatSloganHomepage_AR\":\"\"}",
"{\"vCatTitleHomepage_EN\":\"\",\"vCatTitleHomepage_HI\":\"\",\"vCatTitleHomepage_AR\":\"\"}",
"personal_driver_home_banner.jpg",
"{\"vServiceCatTitleHomepage_EN\":\"Personal Driver\",\"vServiceCatTitleHomepage_HI\":\"निजी ड्राइवर\",\"vServiceCatTitleHomepage_AR\":\"سائق شخصي\",\"vServiceCatTitleHomepage_FR\":\"Chauffeur Personnel\",\"vServiceCatTitleHomepage_ES\":\"Conductor Personal\",\"vServiceCatTitleHomepage_DE\":\"Persönlicher Fahrer\",\"vServiceCatSubTitleHomepage_EN\":\"Hire a professional personal driver for your journeys. Whether it's for daily commute, long trips, or special occasions, get a dedicated driver at your service.\",\"vServiceCatSubTitleHomepage_HI\":\"अपनी यात्राओं के लिए एक पेशेवर निजी ड्राइवर को किराए पर लें। चाहे वह दैनिक यात्रा के लिए हो, लंबी यात्रा के लिए या विशेष अवसरों के लिए, अपनी सेवा में एक समर्पित ड्राइवर प्राप्त करें।\",\"vServiceCatSubTitleHomepage_AR\":\"استأجر سائقًا شخصيًا محترفًا لرحلاتك. سواء كان ذلك للتنقل اليومي أو الرحلات الطويلة أو المناسبات الخاصة ، احصل على سائق مخصص في خدمتك.\"}",
"personal_driver_service_banner.jpg",
"Icon",
"{\"tListDescription_EN\":\"\",\"tListDescription_HI\":\"\",\"tListDescription_AR\":\"\"}",
"","ic_personal_driver_list.png","ic_personal_driver_list2.png","",
"No",
"No",
"",
"{\"tPromoteBannerTitle_EN\":\"\",\"tPromoteBannerTitle_HI\":\"\",\"tPromoteBannerTitle_AR\":\"\"}",
"personal_driver_our_services.png",
"No",
"0.00",
"",
"0.00",
"",
"No",
"",
"",
"0"
);

-- Note: You'll need to add the actual image files to your server's upload directory
-- Default placeholder images are specified above
